# Minimal Render Blueprint – FastAPI only

services:
  - type: web
    name: car-auction-api
    env: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerCommand: gunicorn app.main:app \
      --workers 2 \
      --worker-class uvicorn.workers.UvicornWorker \
      --bind 0.0.0.0:$PORT
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://car-auction-analyzer-isaac.netlify.app
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO

