# Car Auction Analyzer - Render Blueprint
# Simple configuration for reliable deployment

services:
  - type: web
    name: car-auction-api
    runtime: python
    # Install the lightweight dependency set optimised for Render
    buildCommand: cd backend && pip install -r requirements-render.txt
    # Run the simplified FastAPI entry-point
    startCommand: cd backend && uvicorn simple_main:app --host 0.0.0.0 --port $PORT
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://car-auction-analyzer-isaac.netlify.app
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: backend
    autoDeploy: true
