# Car Auction Analyzer - Render.com Deployment Blueprint
services:
  # Main FastAPI Backend Service
  - type: web
    name: car-auction-api
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerCommand: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    healthCheckPath: /api/health
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-auction-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: car-auction-redis
          type: redis
          property: connectionString
      - key: MINIO_ENDPOINT
        sync: MINIO_ENDPOINT
      - key: MINIO_ACCESS_KEY
        sync: MINIO_ACCESS_KEY
      - key: MINIO_SECRET_KEY
        sync: MINIO_SECRET_KEY
      - key: MINIO_BUCKET_IMAGES
        value: vehicle-images
      - key: GOOGLE_CLOUD_VISION_API_KEY
        sync: GOOGLE_CLOUD_VISION_API_KEY
      - key: AZURE_COMPUTER_VISION_KEY
        sync: AZURE_COMPUTER_VISION_KEY
      - key: AZURE_COMPUTER_VISION_ENDPOINT
        sync: AZURE_COMPUTER_VISION_ENDPOINT
      - key: IMAGGA_API_KEY
        sync: IMAGGA_API_KEY
      - key: IMAGGA_API_SECRET
        sync: IMAGGA_API_SECRET
      - key: KBB_API_KEY
        sync: KBB_API_KEY
      - key: EDMUNDS_API_KEY
        sync: EDMUNDS_API_KEY
      - key: MITCHELL_API_KEY
        sync: MITCHELL_API_KEY
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://car-auction-analyzer-isaac.netlify.app
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

  # Celery Worker for AI Analysis
  - type: worker
    name: car-auction-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerCommand: celery -A app.worker.celery worker --loglevel=info --concurrency=2
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-auction-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: car-auction-redis
          type: redis
          property: connectionString
      - key: MINIO_ENDPOINT
        sync: MINIO_ENDPOINT
      - key: MINIO_ACCESS_KEY
        sync: MINIO_ACCESS_KEY
      - key: MINIO_SECRET_KEY
        sync: MINIO_SECRET_KEY
      - key: MINIO_BUCKET_IMAGES
        value: vehicle-images
      - key: GOOGLE_CLOUD_VISION_API_KEY
        sync: GOOGLE_CLOUD_VISION_API_KEY
      - key: AZURE_COMPUTER_VISION_KEY
        sync: AZURE_COMPUTER_VISION_KEY
      - key: AZURE_COMPUTER_VISION_ENDPOINT
        sync: AZURE_COMPUTER_VISION_ENDPOINT
      - key: IMAGGA_API_KEY
        sync: IMAGGA_API_KEY
      - key: IMAGGA_API_SECRET
        sync: IMAGGA_API_SECRET
      - key: KBB_API_KEY
        sync: KBB_API_KEY
      - key: EDMUNDS_API_KEY
        sync: EDMUNDS_API_KEY
      - key: MITCHELL_API_KEY
        sync: MITCHELL_API_KEY
      - key: SECRET_KEY
        fromService:
          name: car-auction-api
          type: web
          envVarKey: SECRET_KEY
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO

  # Celery Beat Scheduler
  - type: worker
    name: car-auction-beat
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerCommand: celery -A app.worker.celery beat --loglevel=info
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-auction-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: car-auction-redis
          type: redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO

  # Flower - Celery Monitoring
  - type: web
    name: car-auction-flower
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerCommand: celery -A app.worker.celery flower --port=$PORT
    repo: https://github.com/IsaacTheInventor/car-auction-analyzer
    branch: master
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: car-auction-redis
          type: redis
          property: connectionString
      - key: FLOWER_BASIC_AUTH
        sync: FLOWER_BASIC_AUTH

  # Redis for Celery and Caching
  - type: redis
    name: car-auction-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter
    maxmemoryPolicy: volatile-lru

# PostgreSQL Database
databases:
  - name: car-auction-db
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: 15

# Shared Environment Variables
envVarGroups:
  - name: car-auction-analyzer-env
    envVars:
      - key: MINIO_ENDPOINT
        value: play.min.io
        # Replace with your own MinIO/S3 endpoint in production
      - key: MINIO_ACCESS_KEY
        generateValue: true
      - key: MINIO_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLOUD_VISION_API_KEY
        value: ""
        # Add your Google Cloud Vision API key
      - key: AZURE_COMPUTER_VISION_KEY
        value: ""
        # Add your Azure Computer Vision key
      - key: AZURE_COMPUTER_VISION_ENDPOINT
        value: ""
        # Add your Azure Computer Vision endpoint
      - key: IMAGGA_API_KEY
        value: ""
        # Add your Imagga API key
      - key: IMAGGA_API_SECRET
        value: ""
        # Add your Imagga API secret
      - key: KBB_API_KEY
        value: ""
        # Add your KBB API key
      - key: EDMUNDS_API_KEY
        value: ""
        # Add your Edmunds API key
      - key: MITCHELL_API_KEY
        value: ""
        # Add your Mitchell API key
      - key: FLOWER_BASIC_AUTH
        value: "admin:admin"
        # Change to a secure username:password in production
